# Generated by Django 2.1.7 on 2019-03-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenfapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='recetas',
            name='cantidad_Ing_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recetas',
            name='ingrediente_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recetas',
            name='tipo_Cant_Ing_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='cantidad_Ing_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='ingrediente_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='tipo_Cant_Ing_1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
