# Generated by Django 2.1.7 on 2019-03-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenfapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipCant',
        ),
        migrations.RemoveField(
            model_name='recetas',
            name='ingredientes',
        ),
        migrations.AddField(
            model_name='ingredientes',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingredientes',
            name='recetas',
            field=models.ManyToManyField(to='greenfapp.Recetas'),
        ),
    ]
