# Generated by Django 2.1.7 on 2019-04-06 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenfapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_cantidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cantidad', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipo_Cantidad',
            },
        ),
        migrations.AddField(
            model_name='ingredientes',
            name='tip_cant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='greenfapp.Tipo_cantidad'),
        ),
    ]
