# Generated by Django 2.1.7 on 2019-03-28 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenfapp', '0002_auto_20190328_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_cantidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cantidad', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipo_Cantidad',
            },
        ),
        migrations.AddField(
            model_name='ingredientes',
            name='tipo_cantidad',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='greenfapp.Tipo_cantidad'),
            preserve_default=False,
        ),
    ]
