# Generated by Django 2.1.7 on 2019-03-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenfapp', '0003_auto_20190328_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientes',
            name='recetas',
        ),
        migrations.AddField(
            model_name='recetas',
            name='recetas',
            field=models.ManyToManyField(to='greenfapp.Ingredientes'),
        ),
    ]
