# Generated by Django 2.1.7 on 2019-03-31 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenfapp', '0004_auto_20190331_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recetas',
            old_name='recetas',
            new_name='ingredientes',
        ),
    ]
