# Generated by Django 2.1.7 on 2019-03-07 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenfapp', '0005_auto_20190307_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recetas',
            old_name='tipo_Cant_Ing_3',
            new_name='tipo_Cant_Ing_2',
        ),
    ]
