# Generated by Django 2.1.7 on 2019-03-07 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenfapp', '0006_auto_20190307_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recetas',
            name='ingrediente_2',
        ),
    ]
