# Generated by Django 2.1.7 on 2019-03-07 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenfapp', '0007_remove_recetas_ingrediente_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recetas',
            name='cantidad_Ing_2',
        ),
        migrations.RemoveField(
            model_name='recetas',
            name='tipo_Cant_Ing_2',
        ),
    ]
