# Generated by Django 2.1.7 on 2019-03-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenfapp', '0010_auto_20190307_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientes',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='plato',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='tipo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
