# Generated by Django 2.1.7 on 2019-03-07 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenfapp', '0011_auto_20190307_2054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredientes',
        ),
    ]
