# Generated by Django 2.1.7 on 2019-03-07 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenfapp', '0013_auto_20190307_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetas',
            name='cantidad_Ing_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recetas',
            name='ingrediente_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recetas_requests_created', to='greenfapp.Ingredientes'),
        ),
        migrations.AddField(
            model_name='recetas',
            name='tipo_Cant_Ing_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
