# Generated by Django 2.1.7 on 2019-03-08 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenfapp', '0015_auto_20190308_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipCant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipcant', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='recetas',
            name='tipo_Cant_Ing_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='greenfapp.TipCant'),
        ),
    ]
