# Generated by Django 2.1.7 on 2019-03-08 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenfapp', '0016_auto_20190308_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='ingrediente_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recetas_requests_created1a', to='greenfapp.Ingredientes'),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='ingrediente_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recetas_requests_created2a', to='greenfapp.Ingredientes'),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='ingrediente_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recetas_requests_created3a', to='greenfapp.Ingredientes'),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='tipo_Cant_Ing_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recetas_requests_created1b', to='greenfapp.TipCant'),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='tipo_Cant_Ing_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recetas_requests_created2b', to='greenfapp.TipCant'),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='tipo_Cant_Ing_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recetas_requests_created3b', to='greenfapp.TipCant'),
        ),
    ]
