# Generated by Django 2.1.7 on 2019-03-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenfapp', '0018_auto_20190308_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetas',
            name='elaboracion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='plato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
